# Generated by Django 4.0.4 on 2022-06-03 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reducer',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=3000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
